Repository TEAMJEFF/unarmed, pull requests merged in 2018-03, with the labels that each got.

#40 Pause menu issue
  Assets/ExitGame.cs
  Assets/GrapplingHook.cs
  Assets/LevelOne.unity
  Assets/PauseMenuPrefab.prefab
  Assets/PauseMenuPrefab.prefab.meta
  Assets/PausingScript.cs
  Assets/TextureTesting.unity
Labels: UI, bug, design

#60 Repel upgrades
  Assets/LevelOne.unity
  Assets/Libraries/Standard Assets/Characters/ThirdPersonCharacter/Scripts/ThirdPersonUserControl.cs
  Assets/Scripts/Core Mechanics/RepelBlast.cs
  Assets/Scripts/Core Mechanics/RepelBlast.cs.meta
  Assets/Scripts/Core Mechanics/RepelGun.cs
Labels: PRs

#62 Slowtime fps
  Assets/Libraries/Standard Assets/Characters/ThirdPersonCharacter/Scripts/ThirdPersonUserControl.cs
Labels: PRs

#67 Check point
  Assets/Scripts/Core Mechanics/CheckPoint.cs
  Assets/Scripts/Core Mechanics/CheckPoint.cs.meta
  Assets/Scripts/Meta Mechanics/BoundsHandler.cs
  Assets/Scripts/Meta Mechanics/ObjectReset.cs
  Assets/Scripts/Meta Mechanics/ObjectReset.cs.meta
  Assets/Scripts/Meta Mechanics/ResetClass.cs
  Assets/Scripts/Meta Mechanics/ResetClass.cs.meta
  Assets/Scripts/Meta Mechanics/ScreenFader.cs
  Assets/Scripts/UI/RestartCheckPointButton.cs
  Assets/Scripts/UI/RestartCheckPointButton.cs.meta
  Assets/Scripts/UI/restartButton.cs
Labels: Pri: HIGH, mechanic

#69 Screen shake
  Assets/LevelOne.unity
  Assets/Scripts/Core Mechanics/RepelBlast.cs
  Assets/Scripts/ThirdPersonCamera.cs
  Assets/Scripts/UI/CameraShake.cs
  Assets/Scripts/UI/CameraShake.cs.meta
  Assets/Scripts/UI/EZ Camera Shake.meta
  Assets/Scripts/UI/EZ Camera Shake/Scripts.meta
  Assets/Scripts/UI/EZ Camera Shake/Scripts/CameraShakeInstance.cs
  Assets/Scripts/UI/EZ Camera Shake/Scripts/CameraShakeInstance.cs.meta
  Assets/Scripts/UI/EZ Camera Shake/Scripts/CameraShakePresets.cs
  Assets/Scripts/UI/EZ Camera Shake/Scripts/CameraShakePresets.cs.meta
  Assets/Scripts/UI/EZ Camera Shake/Scripts/CameraShaker.cs
  Assets/Scripts/UI/EZ Camera Shake/Scripts/CameraShaker.cs.meta
  Assets/Scripts/UI/EZ Camera Shake/Scripts/Utilities.meta
  Assets/Scripts/UI/EZ Camera Shake/Scripts/Utilities/CameraUtilities.cs
  Assets/Scripts/UI/EZ Camera Shake/Scripts/Utilities/CameraUtilities.cs.meta
  ProjectSettings/ProjectVersion.txt
Labels: Pri: HIGH, mechanic

#70 Slow time effects amaze
  Assets/Libraries/Standard Assets/Characters/ThirdPersonCharacter/Scripts/ThirdPersonUserControl.cs
  Assets/Models/FPSController.prefab
  Assets/Models/FPSController.prefab.meta
  Assets/Models/ThirdPersonController.prefab
  Assets/Models/ThirdPersonController.prefab.meta
  Assets/Scripts/ThirdPersonCamera.cs
  Assets/Sound/SFX.meta
  Assets/Sound/SFX/SLOWTIME_Heartbeat.ogg
  Assets/Sound/SFX/SLOWTIME_Heartbeat.ogg.meta
Labels: PRs
